export const GET_ALL_FOODS = "GET_ALL_FOODS"
export const GET_FILTER_FOODS ="GET_FILTER_FOODS"
export const SEARCH = "SEARCH"
export const GET_DETAILS = "GET_DETAILS"
export const ADDSHOPPING ="ADDSHOPPING"
export const POST_USER ="POST_USER"
export const URL_API ="http://localhost:3001/"